/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttributionRouteImport } from './routes/attribution'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EnforcementRouteImport } from './routes/enforcement'
import { Route as HealthRouteImport } from './routes/health'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttributionRoute = AttributionRouteImport.update({
  id: '/attribution',
  path: '/attribution',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EnforcementRoute = EnforcementRouteImport.update({
  id: '/enforcement',
  path: '/enforcement',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attribution': typeof AttributionRoute
  '/dashboard': typeof DashboardRoute
  '/enforcement': typeof EnforcementRoute
  '/health': typeof HealthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attribution': typeof AttributionRoute
  '/dashboard': typeof DashboardRoute
  '/enforcement': typeof EnforcementRoute
  '/health': typeof HealthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attribution': typeof AttributionRoute
  '/dashboard': typeof DashboardRoute
  '/enforcement': typeof EnforcementRoute
  '/health': typeof HealthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attribution'
    | '/dashboard'
    | '/enforcement'
    | '/health'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attribution'
    | '/dashboard'
    | '/enforcement'
    | '/health'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/attribution'
    | '/dashboard'
    | '/enforcement'
    | '/health'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttributionRoute: typeof AttributionRoute
  DashboardRoute: typeof DashboardRoute
  EnforcementRoute: typeof EnforcementRoute
  HealthRoute: typeof HealthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attribution': {
      id: '/attribution'
      path: '/attribution'
      fullPath: '/attribution'
      preLoaderRoute: typeof AttributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enforcement': {
      id: '/enforcement'
      path: '/enforcement'
      fullPath: '/enforcement'
      preLoaderRoute: typeof EnforcementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttributionRoute: AttributionRoute,
  DashboardRoute: DashboardRoute,
  EnforcementRoute: EnforcementRoute,
  HealthRoute: HealthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
